"""Add translation fields to products and categories

Revision ID: 18dad5557ec7
Revises: 5b1a32355fc8
Create Date: 2025-11-14 11:49:00.788117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18dad5557ec7'
down_revision: Union[str, None] = '5b1a32355fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('categories', sa.Column('description_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('name_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('description_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('short_description_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'short_description_translations')
    op.drop_column('products', 'description_translations')
    op.drop_column('products', 'name_translations')
    op.drop_column('categories', 'description_translations')
    op.drop_column('categories', 'name_translations')
    # ### end Alembic commands ###
