"""Add product enhancements and reviews

Revision ID: 5b1a32355fc8
Revises: 0e063271d766
Create Date: 2025-11-13 22:19:20.794539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b1a32355fc8'
down_revision: Union[str, None] = '0e063271d766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('verified_purchase', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_reviews_id'), 'product_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_product_reviews_product_id'), 'product_reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_reviews_user_id'), 'product_reviews', ['user_id'], unique=False)
    op.add_column('products', sa.Column('key_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('brand', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('warranty_months', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('products', sa.Column('delivery_time_days', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('rating_average', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('products', sa.Column('rating_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rating_count')
    op.drop_column('products', 'rating_average')
    op.drop_column('products', 'delivery_time_days')
    op.drop_column('products', 'weight_kg')
    op.drop_column('products', 'warranty_months')
    op.drop_column('products', 'brand')
    op.drop_column('products', 'key_features')
    op.drop_index(op.f('ix_product_reviews_user_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_product_id'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_id'), table_name='product_reviews')
    op.drop_table('product_reviews')
    # ### end Alembic commands ###
